### ISSUE TITLE
[INGEN] openEHR terminologies not loaded

### ISSUE THREAD

**Issue by jkryszyn** [ppazos/openEHR-OPT#133]
Hi,
I am trying to use ingen tool. I build & run it on Windows with Java 1.8_0_321, Groovy 2.5.15, Gradle 6.4.1. I invoke it like this:

```
opt.bat ingen Observation.opt folder
```

where `opt.bat` is modified and uses valid paths to libraries.

I get the following error:

```
Observation.opt VALID

Exception in thread "main" java.lang.Exception: openEHR terminologies not loaded
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
        at com.cabolabs.openehr.terminology.TerminologyParser.getRubric(TerminologyParser.groovy:108)
        at com.cabolabs.openehr.terminology.TerminologyParser$getRubric$1.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
        at com.cabolabs.openehr.opt.instance_generator.RmInstanceGenerator.generateComposition(RmInstanceGenerator.groovy:305)
        at com.cabolabs.openehr.opt.instance_generator.RmInstanceGenerator.generateVersionFromOPT(RmInstanceGenerator.groovy:246)
        at com.cabolabs.openehr.opt.instance_generator.RmInstanceGenerator$generateVersionFromOPT.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
        at com.cabolabs.openehr.opt.Main$_generateInstances_closure8.doCall(Main.groovy:505)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:421)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2331)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2316)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2357)
        at org.codehaus.groovy.runtime.dgm$186.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:244)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at com.cabolabs.openehr.opt.Main.generateInstances(Main.groovy:499)
        at com.cabolabs.openehr.opt.Main$generateInstances$2.callStatic(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:196)
        at com.cabolabs.openehr.opt.Main.main(Main.groovy:142)
```

What's wrong? I attach the zipped opt file. I've created it using Template Designer and it's sample repository.
[Observation.zip](https://github.com/ppazos/openEHR-OPT/files/7948699/Observation.zip)

I tried to use `ingen` with opt delivered with EHRserver, but I get the same error.

**Comment by jkryszyn** [comment]
The same opt file works well with ingen on Ubuntu. Seems that there is Windows-specific bug in the tool.

**Comment by ppazos** [comment]
Hi @jkryszyn it seems under windows these files are not loaded https://github.com/ppazos/openEHR-OPT/tree/master/src/main/resources/terminology

Maybe has something to do with the paths. Unfortunately I don't have a windows box to test this.

**Comment by jkryszyn** [comment]
Seems like it. I am not a groovy developer so I am afraid I can't contribute. I've tried few things but nothing worked, sometimes just different errors.

I had to change following lines in all test/* groovy files in order to pass all tests during build:

```groovy
getClass().getResource(arg))
```

to 

```groovy
getClass().getClassLoader().getResource(arg))
```

I've tried similar trick in the regular src files, but with no luck. `getClass().getClassLoader()` returns null in the Main class.

**Comment by ppazos** [comment]
Thanks, I'll try to print the path of the resource to see if you windows box prints a Linux path intact of the windows one. I'm sure this is the issue! @jkryszyn

**Comment by ricardofago** [comment]
I think the issue is due to using "\\" as file system path separator in Windows:
https://github.com/ppazos/openEHR-OPT/blob/5fa9a9407a38a7eb901dc1f780977ae058343870/src/main/groovy/com/cabolabs/openehr/opt/instance_generator/RmInstanceGenerator.groovy#L188-L190
Maybe it doesn't like an absolute path without an explicit drive letter, not sure. Using "/" as in
https://github.com/ppazos/openEHR-OPT/blob/5fa9a9407a38a7eb901dc1f780977ae058343870/src/main/groovy/com/cabolabs/openehr/opt/Main.groovy#L431
Should work just fine.

**Comment by ppazos** [comment]
Hi @ricardofago in the first link PS is used which is `static String PS = File.separator`, that should be windows or linux separator (Java returns the right one).

But using PS at the beginning of the path doesn't mean the path is absolute, it is relative to the resources folder, which should be something like src/main/resources

I trust the terminology paths to be correct under windows, though I can't test it because i don't have a windows box.

The XSD for sure I need to update that to use the `PS`.

**Comment by jkryszyn** [comment]
I bet it has something to do with this thread: https://stackoverflow.com/questions/16570523/getresourceasstream-returns-null

Apparently there is a difference if you use `this.getClass().getResourceAsStream()` or `this.class.getResourceAsStream()` - in one case a path has to be preceded with /, in other not. Depending on the method, resources are searched in jar or other place. Unfortunately I don't have proper Java/Groovy environment to debug this, but I'll to set it up and check.

**Comment by ppazos** [comment]
@jkryszyn I'll test it ASAP. One note is in Groovy accessing a field like .xxx does execute .getXXX() internally, though I don't know if the case of .class and .getClass() is an exception to that.

**Comment by ppazos** [comment]
@jkryszyn can you please try to use just '/' in the resource path?

I don't have a windows box so I can't test it. These lines:

https://github.com/ppazos/openEHR-OPT/blob/master/src/main/groovy/com/cabolabs/openehr/opt/instance_generator/RmInstanceGenerator.groovy#L191-L193

Try just:

```
      terminology.parseTerms(getClass().getResourceAsStream("/terminology/openehr_terminology_en.xml"))
      terminology.parseTerms(getClass().getResourceAsStream("/terminology/openehr_terminology_es.xml"))
      terminology.parseTerms(getClass().getResourceAsStream("/terminology/openehr_terminology_pt.xml"))
```

Note you need to build the project the run the instance generator. BTW please check the opt.sh since the opt.bat wasn't updated in a while.

Reference: https://stackoverflow.com/questions/15662820/getresource-puts-a-leading-before-the-disk-name-using-java-1-7-windows-7

**Comment by jkryszyn** [comment]
@ppazos yup, the fix you posted works (previous execution with errors was made before I made a fix in the code):
![openehr_opt](https://user-images.githubusercontent.com/2608018/220877334-5e13f536-5d12-4380-81a8-0a5a104d4348.PNG)

BTW, the proper opt.bat is below:

```
java -cp "./lib/*;%GROOVY_HOME%/lib/*;./build/libs/opt-1.8.19.jar" com.cabolabs.openehr.opt.Main %1 %2 %3 %4 %5 %6 %7
```

**Comment by ppazos** [comment]
Thanks @jkryszyn did you just change the PS for '/'? Just verifying that's the only change.

**Comment by jkryszyn** [comment]
Yes. On the picture's  background you can see Visual Studio Code with openEHR-OPT code which was compiled. I modified only those three lines which you pointed to.

**Comment by ppazos** [comment]
This was fixed in the current master. Release 1.8.24 should have the fixes inside. @jkryszyn note I'm building now with JDK11 instead of JDK8 as before since I'm updating all my openEHR related projects to JDK11.
