### ISSUE TITLE
RmValidator2: exception when committing multiple structured compo

### ISSUE THREAD

**Issue by ppazos** [ppazos/openEHR-OPT#162]
```
Cannot invoke method has() on null object. Stacktrace follows:

java.lang.reflect.InvocationTargetException: null
        at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:54)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: Cannot invoke method has() on null object
        at com.cabolabs.openehr.validation.RmValidator2.validate_single_attribute(RmValidator2.groovy:2212)
        at com.cabolabs.openehr.validation.RmValidator2.validate(RmValidator2.groovy:1055)
        at com.cabolabs.openehr.validation.RmValidator2$_validate_closure3.doCall(RmValidator2.groovy:456)
        at com.cabolabs.openehr.validation.RmValidator2.validate(RmValidator2.groovy:337)
        at com.cabolabs.openehr.validation.RmValidator2.validate_multiple_attribute(RmValidator2.groovy:2072)
        at com.cabolabs.openehr.validation.RmValidator2.validate(RmValidator2.groovy:1007)
        at com.cabolabs.openehr.validation.RmValidator2$_validate_closure3.doCall(RmValidator2.groovy:456)
        at com.cabolabs.openehr.validation.RmValidator2.validate(RmValidator2.groovy:337)
        at com.cabolabs.openehr.validation.RmValidator2.validate_multiple_attribute(RmValidator2.groovy:2072)
        at com.cabolabs.openehr.validation.RmValidator2.validate(RmValidator2.groovy:867)
        at com.cabolabs.openehr.validation.RmValidator2.validate_alternatives(RmValidator2.groovy:849)
        at com.cabolabs.openehr.validation.RmValidator2.validate(RmValidator2.groovy:839)
        at com.cabolabs.openehr.validation.RmValidator2.validate_single_attribute(RmValidator2.groovy:2194)
        at com.cabolabs.openehr.validation.RmValidator2.validate(RmValidator2.groovy:632)
        at com.cabolabs.openehr.validation.RmValidator2$_validate_closure3.doCall(RmValidator2.groovy:456)
        at com.cabolabs.openehr.validation.RmValidator2.validate(RmValidator2.groovy:337)
        at com.cabolabs.openehr.validation.RmValidator2.validate_multiple_attribute(RmValidator2.groovy:2072)
        at com.cabolabs.openehr.validation.RmValidator2.validate(RmValidator2.groovy:602)
        at com.cabolabs.openehr.validation.RmValidator2.validate_alternatives(RmValidator2.groovy:584)
        at com.cabolabs.openehr.validation.RmValidator2.validate(RmValidator2.groovy:574)
        at com.cabolabs.openehr.validation.RmValidator2.validate_single_attribute(RmValidator2.groovy:2194)
        at com.cabolabs.openehr.validation.RmValidator2.validate(RmValidator2.groovy:563)
        at com.cabolabs.openehr.validation.RmValidator2$_validate_closure3.doCall(RmValidator2.groovy:456)
        at com.cabolabs.openehr.validation.RmValidator2.validate(RmValidator2.groovy:337)
        at com.cabolabs.openehr.validation.RmValidator2.validate_multiple_attribute(RmValidator2.groovy:2072)
        at com.cabolabs.openehr.validation.RmValidator2.validate(RmValidator2.groovy:510)
        at com.cabolabs.openehr.validation.RmValidator2.dovalidate(RmValidator2.groovy:135)
        at com.cabolabs.ehrserver.api.OpenEhrRestService.$tt__validate(OpenEhrRestService.groovy:165)
        at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
        at com.cabolabs.ehrserver.api.OpenEhrRestCompositionService.$tt__create_composition(OpenEhrRestCompositionService.groovy:51)
        at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
        at com.cabolabs.ehrserver.api.OpenEhrRestController.$tt__create_composition(OpenEhrRestController.groovy:868)
        at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
        at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
        ... 14 common frames omitted

```

**Comment by ppazos** [comment]
The issue was with the completed() OPTs that were not adding the existence and occurrences intervals for the completed attributes and c_objects.

**Comment by ppazos** [comment]
Fixed in https://github.com/ppazos/openEHR-OPT/commit/2069dd979dad0b9181e1af999d4eba5d380342d3
