### ISSUE TITLE
ingen error: C_DATE not supported

### ISSUE THREAD

**Issue by ppazos** [ppazos/openEHR-OPT#44]
```
resource on xsd/OperationalTemplate.xsd = java.io.ByteArrayInputStream@5bc5c9af
2018-07-03 01:56:08.954 ERROR --- [io-8009-exec-10] StackTrace                               : Full Stack Trace:

**java.lang.Exception: primitive C_DATE not supported**
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at **com.cabolabs.openehr.opt.parser.OperationalTemplateParser.parseObjectNode(OperationalTemplateParser.groovy:341)**
	at sun.reflect.GeneratedMethodAccessor852.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at **com.cabolabs.openehr.opt.parser.OperationalTemplateParser$_parseAttributeNode_closure9.doCall(OperationalTemplateParser.groovy:422)**
```

[Sample_Admission_Encounter.opt.txt](https://github.com/ppazos/openEHR-OPT/files/2157347/Sample_Admission_Encounter.opt.txt)

**Comment by ppazos** [comment]
it's working the openEHR-OPT lib was outdated
